#!/bin/bash

if [ -f "${BASH_SOURCE[0]}.cfg" ]; then
    source "${BASH_SOURCE[0]}.cfg"
fi

command="$1" && shift

while (( "$#" )); do
    argument="$1" && shift
    case ${argument} in
        "--theme") theme=$1 && shift;;
        "--target") target=$1 && shift;;
        "--output") output=$1 && shift;;
        *) output=${argument}
    esac
done

theme=${theme:-default}
output=${output:-build}

bold() {
    echo "$(tty -s && tput bold)$1$(tty -s && tput sgr0)" 
}

client_build() {
    node tools/generator.js ${output} --theme ${theme}
}

client_watch() {
    export ENVIRONMENT=development
    client_build
    case "$(uname -s)" in
        Darwin*) 
            if [ -z "$(which fswatch)" ]; then
                brew install fswatch
            fi
            fswatch -r -o . -e "${output}" | while read; do client_build; done
            ;;
    esac
}

case "${command}" in
    "build") client_build $@;;
    "watch") client_watch $@;;
    *)
        echo;
        echo "Usage: $(tty -s && tput bold)$(basename "$0")$(tty -s && tput sgr0) <command> <options>"
        echo
        echo "    build      Build the website"
        echo;
    ;;
esac
